name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: nhutpm219/.github/.github/workflows/workflow-use-output.yml@master
  
  echo_the_params:
    uses: nhutpm219/.github/.github/workflows/test-workflow-1.yml@master
    with:
      the-parameters-1: input params 1 from child repo
      the-parameters-2: input params 2 from child repo

  echo_the_config_path:
    uses: nhutpm219/.github/.github/workflows/test-workflow-2.yml@master
    with:
      config-path: input the config-path from child repo
    secrets: inherit

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: call_composite_action
        uses: nhutpm219/.github/.github/composite-hello-world-steps@master
        with:
          who-to-greet: 'Alexander the Great'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.call_composite_action.outputs.random-number }}