name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    outputs: 
      app-name: ${{ steps.parse-variable.outputs.app-name }}
      app-type: ${{ steps.parse-variable.outputs.app-type }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Performing parse the variable
        id: parse-variable
        uses: nhutpm219/.github/.github/parse-variable@master
        with:
          file: variables.yml

      - name: Verify output from parse variable
        run: |
          echo "App Name: ${{ steps.parse-variable.outputs.app-name }}"
          echo "App Type: ${{ steps.parse-variable.outputs.app-type }}"

  ci_pipelines:
    needs: read-yaml
    uses: nhutpm219/.github/.github/workflows/ci.yml@master
    with:
      app-name: ${{ needs.read-yaml.outputs.app-name }}
      app-type: ${{ needs.read-yaml.outputs.app-type }}