name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  ci:
    name: Call CI workflows
    uses: nhutpm219/.github/.github/workflows/ci.yml@master
    with:
      app-name: landing page
      app-type: nodejs
